version: "3.9"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: "asana-hire/backend:0.0.1"
    container_name: asana-hire-backend
    environment:
      - ASANA_ACCESS_TOKEN
      - ASANA_APPLICATION_PORTFOLIO_GID
      - ASANA_INTERVIEW_PORTFOLIO_GID
      - ASANA_WORKSPACE_GID
      - DB_PASSWORD
      - DB_URL
      - DB_USERNAME
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - REACT_APP_API_SERVER_URL
      - REACT_APP_CLIENT_URL
      - SPRING_PROFILES_ACTIVE
    ports:
      - "127.0.0.1:8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_SERVER_URL=${REACT_APP_API_SERVER_URL}
    image: "asana-hire/frontend:0.0.1"
    container_name: asana-hire-frontend
    environment:
      - REACT_APP_API_SERVER_URL
    ports:
      - "127.0.0.1:80:80"
