version: '3'
services:
  backend:
    image: "asana-hire/backend:0.0.1"
    container_name: asana-hire-backend
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - asana_access_token
      - project_job_source_gid
      - workspace_gid
      - email_username
      - email_password
  frontend:
    image: "asana-hire/frontend:0.0.1"
    container_name: asana-hire-frontend
    build:
      dockerfile: frontend/Dockerfile
    ports:
      - "127.0.0.1:80:80"
