version: "3.9"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: ghcr.io/conservationcolorado/asana-hire/asana-hire-backend:latest
    environment:
      - ASANA_ACCESS_TOKEN
      - ASANA_APPLICATION_PORTFOLIO_GID
      - ASANA_INTERVIEW_PORTFOLIO_GID
      - ASANA_WORKSPACE_GID
      - DB_PASSWORD
      - DB_URL
      - DB_USERNAME
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SERVER_BASE_URL
      - CLIENT_BASE_URL
      - SPRING_PROFILES_ACTIVE
    ports:
      - "127.0.0.1:8080:8080"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: ghcr.io/conservationcolorado/asana-hire/asana-hire-frontend:latest
    environment:
      - SERVER_BASE_URL
      - CLIENT_BASE_URL
    ports:
      - "127.0.0.1:3000:3000"
