logging:
  level:
    org.springframework.beans: INFO
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        temp.use_jdbc_metadata_defaults: false
        globally_quoted_identifiers: true
        auto_quote_keyword: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${google_client_id}
            clientSecret: ${google_client_secret}
            scope:
              - "https://www.googleapis.com/auth/gmail.modify"
