logging:
  level:
    org.springframework.beans: info
    org.springframework.data.jpa: debug
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        temp.use_jdbc_metadata_defaults: false
        globally_quoted_identifiers: true
        auto_quote_keyword: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-id: ${google_client_id}
            client-secret: ${google_client_secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
              - "https://www.googleapis.com/auth/gmail.modify"
