CREATE TABLE IF NOT EXISTS "USER"
(
    ID       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL,
    PICTURE  VARCHAR(255) NOT NULL,
    PROVIDER VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "JOB"
(
    ID                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE                  VARCHAR(255) NOT NULL,
    APPLICATION_PROJECT_ID VARCHAR(255) NOT NULL,
    INTERVIEW_PROJECT_ID   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "SYNC_EVENT"
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID     BIGINT REFERENCES Job (ID) NOT NULL,
    CREATED_ON TIMESTAMP WITH TIME ZONE   NOT NULL,
    STATUS     VARCHAR(255)               NOT NULL
        CHECK (STATUS IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE'))
);
