# Build and test this project with Maven, caching dependencies to improve the workflow execution time
# Also generate and upload a test report

name: Server CI (Maven)

# Run automatically on pull requests to main
# Run manually from the Actions tab
on:
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out this repo
      - name: Checkout
        uses: actions/checkout@v3

      # Specify JDK and cache Maven dependencies
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build project with Maven
      - name: Install with Maven
        working-directory: backend
        run: mvn --batch-mode -DskipTests package

      # Run tests
      - name: Run tests with Maven
        working-directory: backend
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      # Generate test report
      - name: Generate test report
        uses: dorny/test-reporter@v1
        # Run even if the previous step failed
        if: always()
        with:
          name: asana-hire Test Report
          working-directory: backend
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
