# Build and test this project's front end with npm

name: Client CI (Node.js)

defaults:
  run:
    working-directory: frontend

# Run automatically on pull requests to main
# Run manually from the Actions tab
on:
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
